baseline = {'i_in': 3,
            'c_in': 512,
            'channel_in': 3,
            'channel_base': 64,
            'channel_multiplier': 2.0,
            'channel_max': 1024,
            'num_resample_steps': 5,
            'channel_scale': 1.0,
            'attention_resolutions': (-1,),
            'skip_resolutions': (32, 64),
            'resample_type': 'conv_interpolate_up',
            'adaptive_type': 'scale_shift_gate',
            'skip_type': 'concatenate',
            'resample_gain': 1.0,
            }

baseline_plus_skips = {'i_in': 3,
                       'c_in': 512,
                       'channel_in': 3,
                       'channel_base': 64,
                       'channel_multiplier': 2.0,
                       'channel_max': 1024,
                       'num_resample_steps': 5,
                       'channel_scale': 1.0,
                       'attention_resolutions': (-1,),
                       'skip_resolutions': (16, 32, 64, 128, 256),
                       'resample_type': 'conv_interpolate_up',
                       'adaptive_type': 'scale_shift_gate',
                       'skip_type': 'concatenate',
                       'resample_gain': 1.0,
                       }

baseline_plus_addition_skips = {'i_in': 3,
                                'c_in': 512,
                                'channel_in': 3,
                                'channel_base': 64,
                                'channel_multiplier': 2.0,
                                'channel_max': 1024,
                                'num_resample_steps': 5,
                                'channel_scale': 1.0,
                                'attention_resolutions': (-1,),
                                'skip_resolutions': (16, 32, 64, 128, 256),
                                'resample_type': 'conv_interpolate_up',
                                'adaptive_type': 'scale_shift_gate',
                                'skip_type': 'addition',
                                'resample_gain': 0.5,
                                }

baseline_plus_addition_skips_attention = {'i_in': 3,
                                          'c_in': 512,
                                          'channel_in': 3,
                                          'channel_base': 64,
                                          'channel_multiplier': 2.0,
                                          'channel_max': 1024,
                                          'num_resample_steps': 5,
                                          'channel_scale': 1.0,
                                          'attention_resolutions': (8, 16, 32),
                                          'kv_compress': {8: 1, 16: 1, 32: 1, 64: None, 128: None, 256: None},
                                          'skip_resolutions': (16, 32, 64, 128, 256),
                                          'resample_type': 'conv_interpolate_up',
                                          'adaptive_type': 'scale_shift_gate',
                                          'skip_type': 'addition',
                                          'resample_gain': 0.5,
                                          }

close_up = {'i_in': 3,
            'c_in': 512,
            'channel_in': 3,
            'channel_base': 64,
            'channel_multiplier': 2.0,
            'channel_max': 1024,
            'num_resample_steps': 5,
            'channel_scale': 1.0,
            'attention_resolutions': (-1,),
            'kv_compress': {8: 1, 16: 1, 32: 1, 64: None, 128: None, 256: None},
            'skip_resolutions': (16, 32, 64, 128, 256),
            'resample_type': 'conv_interpolate_up',
            'adaptive_type': 'scale_shift_gate',
            'skip_type': 'addition',
            'resample_gain': 0.5,
            }

baseline_plus_addition_skips_attention_mlp_affine = {'i_in': 3,
                                                     'c_in': 512,
                                                     'channel_in': 3,
                                                     'channel_base': 64,
                                                     'channel_multiplier': 2.0,
                                                     'channel_max': 1024,
                                                     'num_resample_steps': 5,
                                                     'channel_scale': 1.0,
                                                     'attention_resolutions': (8, 16, 32),
                                                     'kv_compress': {8: 1, 16: 1, 32: 1, 64: None, 128: None,
                                                                     256: None},
                                                     'skip_resolutions': (16, 32, 64, 128, 256),
                                                     'resample_type': 'conv_interpolate_up',
                                                     'adaptive_type': 'scale_shift_gate',
                                                     'skip_type': 'addition',
                                                     'adaptive_layer': 'mlp',
                                                     'resample_gain': 0.5,
                                                     }

reconstructor_plus_addition_skips_attention = {'i_in': 3,
                                               'c_in': 512,
                                               'channel_in': 3,
                                               'channel_base': 64,
                                               'channel_multiplier': 2.0,
                                               'channel_max': 1024,
                                               'num_resample_steps': 5,
                                               'channel_scale': 1.0,
                                               'attention_resolutions': (8, 16, 32),
                                               'kv_compress': {8: 1, 16: 1, 32: 1, 64: None, 128: None, 256: None},
                                               'skip_resolutions': (16, 32, 64, 128, 256),
                                               'resample_type': 'conv_interpolate_up',
                                               'adaptive_type': 'scale_shift_gate',
                                               'skip_type': 'addition',
                                               'resample_gain': 0.5,
                                               'mask_layer': False
                                               }

baseline_plus_addition_skips_attention_hq = {'i_in': 3,
                                             'c_in': 512,
                                             'channel_in': 3,
                                             'channel_base': 64,
                                             'channel_multiplier': 2.0,
                                             'channel_max': 1024,
                                             'num_resample_steps': 5,
                                             'channel_scale': 1.0,
                                             'attention_resolutions': (8, 16, 32),
                                             'resolution': 512,
                                             'kv_compress': {8: 1, 16: 1, 32: 1, 64: None, 128: None, 256: None,
                                                             512: None},
                                             'skip_resolutions': (32, 64, 128, 256, 512),
                                             'resample_type': 'conv_interpolate_up',
                                             'adaptive_type': 'scale_shift_gate',
                                             'skip_type': 'addition',
                                             'mapping': True,
                                             'resample_gain': 0.5,
                                             }

baseline_plus_addition_skips_attention_mlp = {'i_in': 3,
                                              'c_in': 512,
                                              'channel_in': 3,
                                              'channel_base': 64,
                                              'channel_multiplier': 2.0,
                                              'channel_max': 1024,
                                              'num_resample_steps': 5,
                                              'channel_scale': 1.0,
                                              'attention_resolutions': (8, 16, 32),
                                              'kv_compress': {8: 1, 16: 1, 32: 1, 64: None, 128: None, 256: None},
                                              'skip_resolutions': (16, 32, 64, 128, 256),
                                              'resample_type': 'conv_interpolate_up',
                                              'adaptive_type': 'scale_shift_gate',
                                              'skip_type': 'addition',
                                              'mapping': True,
                                              'resample_gain': 0.5,
                                              }

baseline_plus_addition_skips_mlp = {'i_in': 3,
                                    'c_in': 512,
                                    'channel_in': 3,
                                    'channel_base': 64,
                                    'channel_multiplier': 2.0,
                                    'channel_max': 1024,
                                    'num_resample_steps': 5,
                                    'channel_scale': 1.0,
                                    'attention_resolutions': (-1,),
                                    'kv_compress': {8: None, 16: None, 32: None, 64: None, 128: None, 256: None},
                                    'skip_resolutions': (16, 32, 64, 128, 256),
                                    'resample_type': 'conv_interpolate_up',
                                    'adaptive_type': 'scale_shift_gate',
                                    'skip_type': 'addition',
                                    'mapping': True,
                                    'resample_gain': 0.5,
                                    }

baseline_plus_addition_skips_attention_plus = {'i_in': 3,
                                               'c_in': 512,
                                               'channel_in': 3,
                                               'channel_base': 64,
                                               'channel_multiplier': 2.0,
                                               'channel_max': 1024,
                                               'num_resample_steps': 5,
                                               'channel_scale': 1.0,
                                               'attention_resolutions': (8, 16, 32, 64, 128),
                                               'kv_compress': {8: 1, 16: 1, 32: 2, 64: 4, 128: 8, 256: None},
                                               'skip_resolutions': (16, 32, 64, 128, 256),
                                               'resample_type': 'conv_interpolate_up',
                                               'adaptive_type': 'scale_shift_gate',
                                               'skip_type': 'addition',
                                               'resample_gain': 0.5,
                                               }

# Diffusion

diffusion_plus_addition_skips_attention_mlp = {'i_in': 3,
                                               'c_in': 512,
                                               'channel_in': 3,
                                               'channel_base': 64,
                                               'channel_multiplier': 2.0,
                                               'channel_max': 1024,
                                               'num_resample_steps': 5,
                                               'channel_scale': 1.0,
                                               'attention_resolutions': (8, 16, 32),
                                               'kv_compress': {8: 1, 16: 1, 32: 1, 64: None, 128: None, 256: None},
                                               'skip_resolutions': (16, 32, 64, 128, 256),
                                               'resample_type': 'conv_interpolate_up',
                                               'adaptive_type': 'scale_shift_gate',
                                               'skip_type': 'addition',
                                               'mapping': True,
                                               'condition_image_in': 0,
                                               }

diffusion_plus_addition_skips_attention = {'i_in': 3,
                                           'c_in': 512,
                                           'channel_in': 3,
                                           'channel_base': 64,
                                           'channel_multiplier': 2.0,
                                           'channel_max': 1024,
                                           'num_resample_steps': 5,
                                           'channel_scale': 1.0,
                                           'attention_resolutions': (8, 16, 32),
                                           'kv_compress': {8: 1, 16: 1, 32: 1, 64: None, 128: None, 256: None},
                                           'skip_resolutions': (16, 32, 64, 128, 256),
                                           'resample_type': 'conv_interpolate_up',
                                           'adaptive_type': 'scale_shift_gate',
                                           'skip_type': 'addition',
                                           'mapping': False,
                                           'condition_image_in': 0,
                                           }
